"""Create staging earthquakes table

Revision ID: 68139ca868d4
Revises: f5abe3110d31
Create Date: 2026-07-27 19:02:33.195763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68139ca868d4'
down_revision: Union[str, Sequence[str], None] = 'f5abe3110d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staging_earthquakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_utc', sa.String(length=20), nullable=True),
    sa.Column('hora_utc', sa.String(length=20), nullable=True),
    sa.Column('latitud', sa.String(length=30), nullable=True),
    sa.Column('longitud', sa.String(length=30), nullable=True),
    sa.Column('profundidad_km', sa.String(length=20), nullable=True),
    sa.Column('magnitud', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staging_earthquakes')
    # ### end Alembic commands ###
